# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [36]:
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array)

one_element = array[1,0,2]
print(one_element)

one_dimension = array[0]
print(one_dimension)

dim_subset = array[1,1,:2]
print(dim_subset)

# [x:] print out dimensions of the array starts at x and goes to the end, and it returns the dimension with [[]](double blankets).
# while [x,] return dimension x only with [] (one square blanket) around it. [x,y] returns row y in dimension x.
test = array[1,]
print(test)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
9
[[1 2 3]
 [4 5 6]]
[10 11]
[[ 7  8  9]
 [10 11 12]]


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [41]:
array = np.random.randint(1,50,10)
print(array)

greater = array > 5
print(greater)

less = array < 9
print(less)

equal = array==17
print(equal)

[45 23 39 35 14 34 48  3 13 33]
[ True  True  True  True  True  True  True False  True  True]
[False False False False False False False  True False False]
[False False False False False False False False False False]


In [59]:
or_combine = (array > 30) | (array < 10)
print(or_combine)

and_combine = (array > 30) & (array < 50)
print(and_combine)

[ True False  True  True False  True  True  True False  True]
[ True False  True  True False  True  True False False  True]


## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [61]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [62]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [63]:
#The documentation is easy to follow and I like that it gives examples.

#I think it's possible that I could use the function from what the help function gives me.

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [68]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.transpose(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [78]:
a = np.random.random((2,2))
print(a)

b= np.resize(a,(2,4))
print(b)

c=np.resize(a,(3,2))
print(c)

[[0.97679581 0.23179308]
 [0.1660521  0.15055486]]
[[0.97679581 0.23179308 0.1660521  0.15055486]
 [0.97679581 0.23179308 0.1660521  0.15055486]]
[[0.97679581 0.23179308]
 [0.1660521  0.15055486]
 [0.97679581 0.23179308]]


In [84]:
a = np.random.random((8,2))
print(a)

b= a.reshape((4,4))
print(b)

[[0.31075869 0.72803371]
 [0.33230893 0.38202589]
 [0.32259553 0.54489459]
 [0.8653793  0.31099841]
 [0.76025812 0.25491946]
 [0.86856399 0.37986592]
 [0.69542078 0.70069707]
 [0.17634947 0.75472922]]
[[0.31075869 0.72803371 0.33230893 0.38202589]
 [0.32259553 0.54489459 0.8653793  0.31099841]
 [0.76025812 0.25491946 0.86856399 0.37986592]
 [0.69542078 0.70069707 0.17634947 0.75472922]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [20]:
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(array)

row =([[1,2,3]],[[1,2,3]])

np.append(array, row, axis=1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 1,  2,  3]]])

In [21]:
colum =([[1],[1]],[[1],[1]])

np.append(array, colum, axis=2)

array([[[ 1,  2,  3,  1],
        [ 4,  5,  6,  1]],

       [[ 7,  8,  9,  1],
        [10, 11, 12,  1]]])

## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [120]:
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [121]:
help(np.delete)

Help on function delete in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
      Input array.
    obj : slice, int or array of ints
      Indicate indices of sub-arrays to remove along the specified axis.
    axis : int, optional
      The axis along which to delete the subarray defined by `obj`.
      If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    append : Append elements at the end of an array.
    
    Notes
    -----
    Often it is preferable to use a boolean mask. For 

In [18]:
a = np.random.random((3,4))
print(a)

i = np.insert(a,4,1, axis =1)
print(i)

i_sequence = np.insert(a,[0], [[1],[2],[3]], axis =1)
print(i_sequence)

[[0.3260321  0.42753026 0.97552997 0.89012465]
 [0.9436089  0.31589356 0.23080393 0.24396898]
 [0.48445596 0.37124719 0.80508602 0.7397714 ]]
[[0.3260321  0.42753026 0.97552997 0.89012465 1.        ]
 [0.9436089  0.31589356 0.23080393 0.24396898 1.        ]
 [0.48445596 0.37124719 0.80508602 0.7397714  1.        ]]
[[1.         0.3260321  0.42753026 0.97552997 0.89012465]
 [2.         0.9436089  0.31589356 0.23080393 0.24396898]
 [3.         0.48445596 0.37124719 0.80508602 0.7397714 ]]


In [37]:
a = np.random.random((3,4))
print(a)

delete = np.delete(a, 2, axis =1)
print(delete)

# delete rows devided by 3.
delete_inbetween = np.delete(a, np.s_[::3], 1)
print(delete_inbetween)

[[0.47826442 0.25113298 0.42635703 0.15670794]
 [0.68190686 0.80978676 0.92461474 0.46519634]
 [0.7705282  0.72596832 0.43629312 0.50533387]]
[[0.47826442 0.25113298 0.15670794]
 [0.68190686 0.80978676 0.46519634]
 [0.7705282  0.72596832 0.50533387]]
[[0.25113298 0.42635703]
 [0.80978676 0.92461474]
 [0.72596832 0.43629312]]


## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [38]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5f: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [50]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

print("\nvsplit:")
print(np.split(my_2d_array, 2, axis =0))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
