# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [37]:
my_1d_array = np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3], [4,5,6]])
my_3d_array = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(my_3d_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [16]:
my_3d_array = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

# Total dimensions of the array
print(my_3d_array.ndim)

# Dimension of the axis
print(my_3d_array.shape)

# Total elements in the array
print(my_3d_array.size)

# Type of data in the array
print(my_3d_array.dtype)

# Length of one array element in bytes
print(my_3d_array.itemsize)

# Buffer object pointing to the start of the array's data
print(my_3d_array.data)

# Total bytes consumed by elements in the array
print(my_3d_array.nbytes)

3
(2, 2, 3)
12
int64
8
96


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [3]:
# print a 2-dimensional array filled with ones with 3 rows and 4 columns
ones = np.ones((3,4))
print(ones)

# print a 2-dimensional array filled with zeros with 3 rows and 4 columns
zeros = np.zeros((3,4))
print(zeros)

# print an empty 2-dimensional array with 3 rows and 4 columns
empty = np.empty((3,4))
print(empty)

# print a 2-dimensional array with 3 rows and 4 columns filled with 2
full = np.full((3,4),2)
print(full)

# print a 1-dimnesional array of values 0 to 9
arange = np.arange(10,)
print(arange)

# return a new array of evenly spaced numbers over the number of intervals given
linspace = np.linspace(1,10, num=5)
print(linspace)

# return a random 3x3 2-dimensional array filled with numbers between 0 and 1.
random = np.random.random((3,3))
print(random)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[0 1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[0.87762473 0.07572386 0.11463464]
 [0.82336717 0.57927279 0.5562766 ]
 [0.06292643 0.24913555 0.28699592]]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [3]:
a = np.ones((1,3,2))
b = np.random.random((3,1))

add = a+b
print(add)

multiply = a*b
print(multiply)

subtract = a-b
print(subtract)

[[[1.88500544 1.88500544]
  [1.10214297 1.10214297]
  [1.92183523 1.92183523]]]
[[[0.88500544 0.88500544]
  [0.10214297 0.10214297]
  [0.92183523 0.92183523]]]
[[[0.11499456 0.11499456]
  [0.89785703 0.89785703]
  [0.07816477 0.07816477]]]


In [6]:
a = np.array((6,3,2))
b = np.array((5,1))

a*b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [93]:
a1 = np.array([1,2,3])
a11 = np.array([4,5,6])

a2 = np.array([[1,2,3],[6,7,8]])

a3 = np.array([[[9,8,7],[6,5,4]],[[3,2,1],[1,1,1]]])

# returns the sum of rows
horizontal = np.sum(a2, axis=1)
print(horizontal)

# returns the sum of columns
vertical = np.sum(a2, axis=0)
print(vertical)

# return a new array of the minimum at each position between a2 and a3
minimum = np.minimum(a2, a3)
print(minimum)

# return a new array of the maximum at each position between a1 and a3
maximum = np.maximum(a1, a3)
print(maximum)

# return the cummulative sum of the elements in the array
cumsum = np.cumsum(a3)
print(cumsum)

# return the cummulative sum of the elements in the array along a given axis
axis_cumsum = np.cumsum(a3, axis = 1)
print(axis_cumsum)

# compute the arithmetic mean along the specified axis
mean = np.mean(a2, axis = 0)
print(mean)

# return Pearson product-moment correlation coefficients between two 1D arrays or one 2D array.
corrcoef = np.corrcoef(a2)
print(corrcoef)

# compute the standard deviation along the specified axis
std = np.std(a2, axis = 0)
print(std)

# compute the variance along the specified axis.
var = np.var(a2, axis = 0)
print(var)


[ 6 21]
[ 7  9 11]
[[[1 2 3]
  [6 5 4]]

 [[1 2 1]
  [1 1 1]]]
[[[9 8 7]
  [6 5 4]]

 [[3 2 3]
  [1 2 3]]]
[ 9 17 24 30 35 39 42 44 45 46 47 48]
[[[ 9  8  7]
  [15 13 11]]

 [[ 3  2  1]
  [ 4  3  2]]]
[3.5 4.5 5.5]
[[1. 1.]
 [1. 1.]]
[2.5 2.5 2.5]
[6.25 6.25 6.25]


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [35]:
a = [True, False, True, False]
b = [True, True, True, False]

# Perform a logical "and" between the elements of the list

np.logical_and(a, b)

array([ True, False,  True, False])

In [33]:
# Perform a logical "or" between the elements of the list

np.logical_or(a, b)

array([ True,  True,  True, False])

In [45]:
# Perform a logical "not" and "and" between the elements of the list

np.logical_not(a and b)

array([False,  True, False,  True])

In [46]:
# Perform a logical "not" and "or" between the elements of the list

np.logical_not(a or b)

array([False,  True, False,  True])